services:
  parser:
    container_name: "parser"
    build:
      context: ./
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: uv run -m src.main
    